### ISSUE TITLE
board_alight.record_use = 0 [complete ridership counts]

### ISSUE THREAD

**Issue by antrim** [ODOT-PTS/GTFS-ride#18]
Current draft:

> * 0 - Entry contains complete ridership counts for the associated stop_id in the field(s) boardings and/or alightings as available.

Might "complete" be misleading or unnecessary? Might a count sometimes be provided which is technically incomplete? The current language appears to imply a standard of quality/accuracy.

**Comment by carletop** [comment]
This language was chosen to indicate that no partial should be entered into this format so that users of the data would be able to reasonably assume completeness at the level of specificity indicated (stop-visit level). That is not to say all ridership is represented, but at least all ridership for the associated unique trip_id, stop-id, stop_sequence combination. This was also chosen to indicate that counts, and not averages or estimations, should be used.

**Comment by carletop** [comment]
I will go ahead and close this issue for now, but feel free to reopen if more discussion is needed.
