### ISSUE TITLE
rider_trip.rider_id --> ride_id [copyediting]

### ISSUE THREAD

**Issue by antrim** [ODOT-PTS/GTFS-ride#20]
Small change, but it seems appropriate to change the **rider_trip.rider_id** field name to **ride_id**. The field doesn't identify an individual rider, and GTFS-ride purports to provide anonymized data.

**Comment by carletop** [comment]
This ID is meant to be associated with a rider so that account specific information can be included (e.g., disabled, military, service animal, etc.). The intent was that the same ID could be seen over multiple trips to deduce transfers and aggregated travel behaviors. The privacy issue inherent in this design has yet to be robustly discussed to any particular solution or consensus of best practices. It was briefly mentioned in the first consortium meeting that such data could be stored in the GTFS-ride format without it necessarily being released as a part of a public GTFS-ride feed.
